---
version: '3.1'

services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=demographic_data
      - POSTGRES_USER=demographic_data
      - POSTGRES_DB=demographic_data
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432